exp_name: change_bs
max_epoch : 60 
rd_seed: 1
n_cls: 6
resolution: 64
ds_rate: 2
mode: epoch
per_val: 10
per_write: 50

num_mini_batch_per_epoch: 1250
num_patches: 15

optimizer:
  type : Adam
  lr   : 0.004
  betas: [0.5, 0.999]
  eps  : 0.000001
  weight_decay: 0

lr_scheduler:
  type: WarmupCosineLR
  max_iters: 50000
  warmup_factor: 0.001
  warmup_iters: 500

loss:
  vp_weight: 100.0
  t_weight: 1.0
  s_weight: 1.0

train_dataset:
  data_dir: data
  sample_num: 2048
  random_rotate: True
  angle_range: 20

train_dataloader:
  bs: 192
  num_workers: 16
  shuffle: True
  drop_last: True
  pin_memory: False

test_dataset:
  data_dir: data
  sample_num: 2048

test_dataloader:
  bs: 1
  num_workers: 0
  shuffle: False
  drop_last: False
